include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_const_constructors: false
    prefer_const_literals_to_create_immutables: false
    avoid_unnecessary_containers: true
    avoid_web_libraries_in_flutter: true
    no_logic_in_create_state: true
    prefer_const_constructors_in_immutables: true
    prefer_const_declarations: true
    prefer_final_fields: true
    unnecessary_const: true
    unnecessary_new: true
    use_key_in_widget_constructors: false

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
