# A basic Codemagic build file for a Flutter Android app.
# The user's provided build.gradle.kts and pubspec.yaml were used as a reference.

workflows:
  my-app-android:
    name: Android Release
    max_build_duration: 60
    instance_type: mac_pro_m1
    
    environment:
      # Flutter version from the user's pubspec.yaml
      flutter: stable
      xcode: 15.3
      cocoapods: default
      
      # Environment variables for Android build
      # The values below are examples, you should use your own signing keys
      vars:
        PACKAGE_NAME: "com.example.my_apmanp"
        ANDROID_KEYSTORE_PATH: /tmp/keystore.jks
        ANDROID_KEYSTORE_PASS: YOUR_KEYSTORE_PASSWORD
        ANDROID_KEY_ALIAS: YOUR_KEY_ALIAS
        ANDROID_KEY_PASS: YOUR_KEY_PASSWORD
      
    scripts:
      # Script to decode the base64-encoded keystore
      - name: Decode Android Keystore
        script: |
          echo $CM_ANDROID_KEYSTORE | base64 --decode > $ANDROID_KEYSTORE_PATH
          
      # Install Flutter dependencies
      - name: Flutter pub get
        script: |
          flutter pub get
          
      # Build the Android App Bundle
      - name: Flutter build release
        script: |
          flutter build apk --release --split-per-abi
          
    artifacts:
      # Artifacts to be published after the build
      - build/app/outputs/flutter-apk/*.apk
