workflows:
  android-app-build:
    name: Build Android APK
    max_build_duration: 120
    instance_type: linux-medium

    environment:
      # هنا لا تحتاج توقيع فعلي إذا سمحت بالـ debug APK
      flutter: stable
      java: 17

    scripts:
      - name: Checkout code
        script: |
          git clone https://github.com/YOUR_GITHUB_USERNAME/YOUR_REPO.git .
      - name: Install dependencies
        script: |
          flutter pub get
      - name: Run code generation (إن وُجد)
        script: |
          flutter pub run build_runner build --delete-conflicting-outputs || echo "no code-gen"
      - name: Build debug APK
        script: |
          flutter build apk --debug --no-tree-shake-icons --verbose

    artifacts:
      - build/app/outputs/flutter-apk/app-debug.apk

    # لا ننشر على متجر Play، فقط نزّل الـAPK من artifacts
