# ملف إعدادات Codemagic لبناء التطبيق
# تم تحسينه لضمان بيئة بناء مستقرة

workflows:
  android-app-build:
    name: Android App Build
    max_build_duration: 120 # زيادة مدة البناء إذا لزم الأمر
    environment:
      flutter: stable
      # تحديد نسخة Java بشكل صريح مهم جداً للتوافق مع أدوات أندرويد الحديثة
      java_version: 17 
    scripts:
      - name: Set up local.properties
        script: | 
          echo "flutter.sdk=$FLUTTER_ROOT" > "$FCI_BUILD_DIR/android/local.properties"
      - name: Get Flutter packages
        script: | 
          flutter clean
          flutter pub get
      - name: Build APK with dynamic versioning
        script: | 
          # استخدام متغيرات البيئة من Codemagic لتحديد رقم الإصدار والبناء
          # يقرأ رقم الإصدار من pubspec.yaml ويستخدم رقم البناء من Codemagic
          flutter build apk --release --build-name=$FLUTTER_PROJECT_VERSION --build-number=$BUILD_NUMBER
    artifacts:
      # المسار الصحيح للـ APK المنتج
      - build/app/outputs/apk/release/app-release.apk
    publishing:
      email:
        recipients:
          - your_email@example.com # استبدل هذا ببريدك الإلكتروني
        notify:
          success: true
          failure: false

