workflows:
  android-app-build:
    name: Android App Build
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      android_signing:
        - keystore_reference
      groups:
        - google_play
      vars:
        PACKAGE_NAME: "com.example.my_apmanp"
        GOOGLE_PLAY_TRACK: internal
      flutter: stable
      java: 17
      xcode: latest
      cocoapods: default
    scripts:
      - name: Set up local.properties
        script: | 
          echo "flutter.sdk=$FLUTTER_ROOT" > "$CM_BUILD_DIR/android/local.properties"
          
      - name: Clean project thoroughly
        script: | 
          # This command is powerful and cleans all generated files.
          flutter clean
          
      - name: Get Flutter packages
        script: | 
          # This is a critical step after cleaning. 
          # It fetches the correct dependencies based on the updated pubspec.yaml and creates a new pubspec.lock file.
          flutter pub get --verbose
          
      - name: Verify dependencies (Optional but good)
        script: | 
          flutter pub deps
          
      - name: Flutter analyze
        script: | 
          flutter analyze
        ignore_failure: true # You can set this to false if you want the build to fail on analysis errors
        
      - name: Build APK
        script: | 
          flutter build apk --release --verbose --no-tree-shake-icons
          
    artifacts:
      - build/app/outputs/apk/release/*.apk
      - build/app/outputs/bundle/release/mapping.txt # Correct path for mapping file
      - flutter_drive.log
      
    publishing:
      email:
        recipients:
          - your_email@example.com
        notify:
          success: true
          failure: false
