name: my_apmanp
description: "تطبيق لإدارة الديون الشخصية يعمل بدون انترنت."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter
  
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.6

  # Database
  sqflite: ^2.3.0
  
  # File handling
  path_provider: ^2.1.1
  
  # State management
  provider: ^6.1.1
  
  # Internationalization
  intl: ^0.20.1
  
  # PDF generation
  pdf: ^3.10.7
  
  # Excel generation
  excel: ^2.1.0
  
  # File operations
  open_filex: ^4.3.4
  
  # Permissions
  permission_handler: ^11.0.1
  
  # UI enhancements
  flutter_slidable: ^3.0.1
  
  # Utilities
  uuid: ^3.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.3

flutter:
  uses-material-design: true
