name: my_apmanp
description: "تطبيق لإدارة الديون الشخصية يعمل بدون انترنت."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter
  
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Database
  sqflite: ^2.3.3+1
  
  # File handling
  path_provider: ^2.1.3
  
  # State management
  provider: ^6.1.2
  
  # Internationalization
  intl: ^0.20.2
  
  # PDF generation
  pdf: ^3.11.0
  
  # Excel generation
  excel: ^4.0.3
  
  # File operations
  open_filex: ^4.4.0
  
  # Permissions
  permission_handler: ^11.3.1
  
  # UI enhancements
  flutter_slidable: ^3.1.0
  
  # Utilities
  # Note: uuid package versioning changed. Version 4.x is the latest.
  uuid: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true
