name: my_apmanp
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  
  # Dependencies for local database, state management, and file operations
  sqflite: ^2.3.3+1
  path_provider: ^2.1.3
  provider: ^6.1.2
  intl: ^0.20.0
  flutter_slidable: ^3.1.0
  share_plus: ^9.0.0
  pdf: ^3.11.0
  open_filex: ^4.3.2
  excel: ^2.1.0
  permission_handler: ^11.3.1
  flutter_localizations:
    sdk: flutter
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  generate: true
